---
title: "AMPs ARGENTINA"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    logo: logo.png
    source_code: embed 
runtime: shiny
---

```{r global, include=FALSE}
#READ both files metadata and percent cover 
library(flexdashboard)
library(leaflet)
library(ggplot2)
library(plotly)
library(spocc)
library(readr)
library(reshape2)
library(xts)
library(dygraphs)
library(plotly)
library(lubridate)
library(dplyr)
library(htmltools)
library(DT)
library(shiny)
library(xts)
library(htmlwidgets)

library(RColorBrewer)
palette(brewer.pal(8, "Set2"))
library(readr)
cover <- read_csv("/Users/gonzalobravo/Documents/GitHub/MBON_CoralNet_Dashboard/DATA/percent_covers.csv") # read cover data
metadata <- read_csv("/Users/gonzalobravo/Documents/GitHub/MBON_CoralNet_Dashboard/DATA/metadata.csv") # read metadata

# Merge photoquadrat.metadata and photoquadrat.cover
AMP <- merge(metadata, cover, by.x = "Name", by.y ="Image name", all.x = TRUE) 

# Remove original data frames from the environment
rm(cover, metadata)

# Reemplazar "CABO DOS BAHIAS" por "PIMCPA_NORTE" en la columna "locality" de AMP
AMP$locality <- ifelse(AMP$locality == "CABO DOS BAHIAS", "PIMCPA_NORTE", AMP$locality)
# Reemplazar "PIMCPA" por "PIMCPA_SUR" en la columna "locality" de AMP
AMP$locality <- ifelse(AMP$locality == "PIMCPA", "PIMCPA_SUR", AMP$locality)

# all seaweed
AMP$algae <- as.numeric(paste(AMP$MAA + AMP$MAEC + AMP$MAEF + AMP$MAEN + AMP$MAF + AMP$MAG + AMP$MALA + AMP$MALCB + AMP$MAS))

# Create long type dataframe 
library(reshape)
AMP_long <- melt(AMP, id.vars = 1:22, measure.vars = 23:ncol(AMP), variable_name = "CATAMI", value_name = "cover", na.rm = TRUE)
# Rename columns because the ontop command is not working 
colnames(AMP_long)[23:24] <- c("CATAMI", "cover")

# Calculate mean, SD, SE for cover data by factors 
library(doBy)
Coverdata <- summaryBy(cover ~ CATAMI + strata, data = AMP_long, FUN = function(x) { c(mean = mean(x), SD = sd(x), SE = sqrt(var(x)/length(x)))})

library(doBy)
Coverdata_AMPs <- summaryBy(cover ~ CATAMI + strata + locality, data = AMP_long, FUN = function(x) { c(mean = mean(x), SD = sd(x), SE = sqrt(var(x)/length(x)))})

library(dplyr)
library(lubridate)
AMP <- AMP %>%
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date)) %>%
  select(Name, Date, year, month, everything())

photo_bydate <- as.data.frame(table(AMP$year, AMP$site, AMP$locality, AMP$strata))
colnames(photo_bydate) <- c("Fecha", "Sitio", "Localidad", "Estrato", "n fotocuadrantes")  

# SST
#getSST.r was used to get data 
## get sampling event dates
samplingDates <- unique(AMP$Date)

## read SST values
library(readr)
SST <- read_csv("/Users/gonzalobravo/Documents/GitHub/MBON_CoralNet_Dashboard/DATA/ISLAPINGUINO_SST.csv")
SST.clim <- read_csv("/Users/gonzalobravo/Documents/GitHub/MBON_CoralNet_Dashboard/DATA/ISLAPINGUINO_Climatology.csv")



library(plotly)
library(dplyr)
library(cols4all)
# Obtener las categorías únicas en la columna 'CATAMI'
categorias_unicas <- unique(Coverdata_AMPs$CATAMI)
num_categorias <- length(categorias_unicas)

# Obtener una paleta de colores de cols4all con 18 colores
paleta_cols4all <- c4a("poly.alphabet", 18)

# Crear un vector de colores asignados a las categorías
colores_categoria <- paleta_cols4all[match(Coverdata_AMPs$CATAMI, categorias_unicas)]

# Asignar los colores al dataframe en una nueva columna llamada 'Color'
Coverdata_AMPs$Color <- colores_categoria

# Obtener las localidades únicas en la columna 'locality'
localidades_unicas <- unique(Coverdata_AMPs$locality)
```

# Mapa

Column {data-width=650}
-------------------------------------
```{r map, fig.width=12, fig.height=8, message=FALSE,message=FALSE, warning=FALSE}
# Crear el mapa
map <- leaflet(AMP)%>%# add different provider tiles
  addProviderTiles(
    "Esri.WorldImagery",
    # give the layer a name
    group = "Satelite"
  ) %>%
  addProviderTiles(
    "OpenStreetMap",
    group = "Mapa para zoom"
  ) %>%
  # add a layers control
  addLayersControl(
    baseGroups = c(
      "Satelite", "Mapa para zoom"),
    # position it on the topleft
    position = "topleft"
  ) %>%# Agregar los iconos de las localidades
  addCircleMarkers(
    data = AMP, 
    ~Longitude, 
    ~Latitude,
    weight = 0.5,
    col = 'red',
    fillColor = 'red',
    radius = 4,
    fillOpacity = 0.5,
    stroke = T,
    popup = ~site,
    clusterOptions = markerClusterOptions())


map  # Mostrar el mapa

```


# Cobertura organismos vivos
```{r taxacover}
# Use this when using percent_covers.csv and full names from CoralNet
# taxacover = AMP_long %>% filter(CATAMI != "Substrate..Consolidated..hard.") %>% 
#   group_by(site, strata, Image.ID) %>% 
#   summarise(sumcover = sum(cover, na.rm=T))

# Use this when using percent_covers_AMP2023.cvs and short names from CoralNet
taxacover = AMP_long %>% filter(CATAMI != "SC", CATAMI !="algae") %>% 
  group_by(locality, strata, Name) %>% 
  summarise(sumcover = sum(cover, na.rm=T))

pp = ggplot(taxacover, aes(x=factor(strata,level=c('LOWTIDE', 'MIDTIDE', 'HIGHTIDE')), sumcover, fill=strata))
pp = pp + geom_boxplot() + ylab("% Cobertura de todas las especies por cuadrante") + xlab("")+
  facet_grid(~locality) + 
  theme_bw(base_size = 10) + theme(legend.position = "none",axis.text.x = element_text(angle = 90, hjust = 1),strip.text = element_text(size = 5))
ggplotly(pp)
```


# Cobertura grupos CATAMI

### Cobertura de grupos CATAMI por nivel intermareal (Bajo, Medio y Alto)

```{r echo=FALSE}
# UI function
localidadPieUI <- function(id) {
  ns <- NS(id)
  fillCol(height = 600, flex = c(NA, 1), 
    inputPanel(
      selectInput(ns("localidad"), "Localidad:", choices = unique(Coverdata_AMPs$locality))
    ),
    plotlyOutput(ns("pieChart"), height = "100%")
  )
}

# Server function
localidadPie <- function(input, output, session, ...) {
  output$pieChart <- renderPlotly({
    localidad <- input$localidad
    
    # Filtrar los datos para la localidad actual
    Coverdata_AMPs_site <- filter(Coverdata_AMPs, locality == localidad)
    
    # Crear un gráfico de torta para cada estrato
    sel_data.L <- filter(Coverdata_AMPs_site, strata == "LOWTIDE", cover.mean > 0, CATAMI != "algae")
    sel_data.M <- filter(Coverdata_AMPs_site, strata == "MIDTIDE", cover.mean > 0, CATAMI != "algae")
    sel_data.H <- filter(Coverdata_AMPs_site, strata == "HIGHTIDE", cover.mean > 0, CATAMI != "algae")
    
    p <- plot_ly(labels = ~CATAMI, values = ~cover.mean, legendgroup = ~CATAMI, textinfo = 'label+percent',
                 marker = list(colors = ~Color)) %>%  # Aquí asignamos los colores desde la columna 'Color'
      add_pie(data = sel_data.L, name = "Bajo", title = 'Estrato Bajo', domain = list(row = 0, column = 0)) %>%
      add_pie(data = sel_data.M, name = "Medio", title = 'Estrato Medio', domain = list(row = 0, column = 1)) %>%
      add_pie(data = sel_data.H, name = "Alto", title = 'Estrato Alto', domain = list(row = 0, column = 2)) %>%
      layout(title = localidad, showlegend = T,
             grid = list(rows = 1, columns = 3),
             xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  })
}

```

```{r}
# Include the pie chart module
localidadPieUI("localidadPie")
callModule(localidadPie, "localidadPie", col = rainbow(20))
```
